### ISSUE TITLE
Apartment

### ISSUE THREAD

**Issue by Svashta** [huacnlee/rails-settings-cached#102]
Hi,

I am using Apartment gem in my app.
I can't figure out how to properly set up rails-settings-gem to work with Apartment.

Does anyone have any experience with it?
Should I put settings model in excluded models or not?

Thx

**Comment by mort666** [comment]
We are using apartment and milia with this gem, it kind of depends on where you want the settings to be used.

We are using the settings for individual users within the tenant therefore we don't have the settings models within the excluded models.

Basically in our case as we have milia tenants inside apartment tenants we have model for settings linked to a milia tenant via their acts_as_tenant. Without the model in the excluded models.

If you want to have the same settings for every tenant drop them in the excluded models, therefore every tenant will share the same settings.

**Comment by sylow** [comment]
Hi @Svashta,

As @mort666 has already explained; It depends on what you are going to store in your Settings.  

1. If you are planning to store global key/values then exclude that model. 
2. If you want to use tenant specific settings then no need to do anything. Just install and use as it is.
3. You can have 2 different models as well for 1 and 2

We have been using Settings in our multi-tenant app for a half year with no problem.
