### ISSUE TITLE
I18n keys translations

### ISSUE THREAD

**Issue by romaslmd** [huacnlee/rails-settings-cached#105]
Got an issue with translations when using keys with dots (e.g.: 'setting_key.en')
Code: `Setting.human_attribute_name('setting_key.en')`

Is there any workaround or maybe is possible to do something like:
```
...
def self.human_attribute_name(attribute, options = {})
  super(attribute.to_s.underscore.tr('.', '_'), options)
end
...
```

**Comment by huacnlee** [comment]
```rb
I18n.t('setting.setting_key.en')
```
