### ISSUE TITLE
404 on key with dots

### ISSUE THREAD

**Issue by romaslmd** [huacnlee/rails-settings-cached#106]
```
# config/routes.rb
resources :settings
```

```
# views/settings/index.html.slim
= link_to 'Edit', edit_setting_path(id: 'site_name.en'), remote: true
```
After click:
> No route matches [GET] "/settings/site_name.en/edit"`

is there any workaround?
is it possible to add kind of slug to settings to use it in `#to_param` method?

**Comment by huacnlee** [comment]
You need change Rails routes.rb to `:id` contains `.`
