### ISSUE TITLE
Destroy Leaves data

### ISSUE THREAD

**Issue by buehlerj** [huacnlee/rails-settings-cached#117]
If I try to do a Setting.destroy :object, it will not be found. However doing Setting.object will return what I assigned it to before destroying.

**Comment by tovodeverett** [comment]
I have been running into the same issue for quite some time.  I've resorted to the following monkey patch:
``` ruby
module RailsSettings
  class Base
    class << self
      def destroy(var_name)
        retval = super
        Rails.cache.delete(cache_key(var_name, @object))
        retval
      end
    end
  end
end
```

That seems to fix it for me!

**Comment by buehlerj** [comment]
Hey thank you very much! I will give it a try! 😃
