### ISSUE TITLE
Setting.foo is different than Setting.find_by_var('foo').value

### ISSUE THREAD

**Issue by brentkearney** [huacnlee/rails-settings-cached#122]
I sometimes find that `Setting.foo` returns a value that is different from `Setting.find_by(var: 'foo').value`. I'm not sure how/when this happens. In my Settings model, I'm removing some keys and values and adding others, then saving with `Setting.merge!(section, new_location)`.

**Comment by huacnlee** [comment]
Because rails-settings-cache wants keep the origianl value type, so that store value with `YAML.dump`, and then when you calling `Setting.foo`, return the value of `YAML.load`.

But the `Setting.find_by(var: 'foo')` way is ActiveRecord way.

**Comment by brentkearney** [comment]
OK, so does this mean that I should never do this?

setting = Setting.find_by_var('foo')
setting.value = 'bar'
setting.save

... because that will break Setting.foo?

**Comment by brentkearney** [comment]
What if I don't know the name of the setting? How can I go through them all and modify them? For example:

    Setting.get_all.keys.each do |var_name|
        s = Setting.find_by_var(var_name)
        s.value = new_value
        s.save
    end

There appears to be no way to save a setting with this format: `Setting.var_name = new_value`, when "var_name" is a variable. Or is there a way to do that?
