### ISSUE TITLE
cannot delete default foo and bar settings

### ISSUE THREAD

**Issue by navjeetc** [huacnlee/rails-settings-cached#125]
I cannot delete the default foo and bar settings. I tried AppConfig.delete_all and AppConfig.destroy_all. How do I remove those two settings?

**Comment by navjeetc** [comment]
Figured out. Those were coming from app.yml. Removed the app.yml file and all is good.

**Comment by jeanfbrito** [comment]
Your question resolved my problem. Thanks alot!
