### ISSUE TITLE
I don't understand why is it called "cached"

### ISSUE THREAD

**Issue by FeloVilches** [huacnlee/rails-settings-cached#130]
Everytime I reload the page, all the queries are performed again. Nothing is being cached. Or is is just a cache per script execution, and after the page (html.erb in my case) is delivered, the cache is lost?

Am I missing something?

**Comment by iarie** [comment]
It uses `ActiveSupport::Cache` under the hood, check your setup, maybe it is disabled in your enviroment.
http://api.rubyonrails.org/classes/ActiveSupport/Cache.html
