### ISSUE TITLE
Please correct in the description

### ISSUE THREAD

**Issue by vortx** [huacnlee/rails-settings-cached#143]
Please correct in the description of "How to create a list, form to manage Settings?".

```
def edit
    get_setting
end
```
otherwise an error will occur.

**Comment by huacnlee** [comment]
```rb
before_action :get_setting, only: [:edit, :update]
```

**Comment by vortx** [comment]
Sorry I completely forgot))) But I still do not work, rails 4.2.6. I sit, I do not update the values

**Comment by huacnlee** [comment]
Here is a real world example:

https://github.com/ruby-china/homeland/blob/master/app/controllers/admin/site_configs_controller.rb
