### ISSUE TITLE
0.7.2 requires config/app.yml to be present

### ISSUE THREAD

**Issue by brentkearney** [huacnlee/rails-settings-cached#148]
Hi! Thanks so much for your work on rails-settings-cached!

After the update from 0.7.1 to 0.7.2, my rails app suddenly stopped booting. I get this error message from rack-loader:

Could not spawn process for application /home/app/workshops: The application encountered the following error: No such file or directory @ rb_sysopen - /home/app/workshops/config/app.yml (Errno::ENOENT)

Doing `touch config/app.yml` worked around this new dependency.

**Comment by Epigene** [comment]
I understand v0.7.3 fixes this, but it is not released? What is up with that?

**Comment by huacnlee** [comment]
You can give a empty file
