### ISSUE TITLE
Why does cache doesn't expire after value is updated?

### ISSUE THREAD

**Issue by AkshayGoyal022** [huacnlee/rails-settings-cached#154]

**Comment by huacnlee** [comment]
How can you update the value?

**Comment by AkshayGoyal022** [comment]
I tried this `Setting.my_setting = "new value"` in my rails console. 

But when i fetched the value using `Setting.my_setting` the return value was still the old value.

After restarting my rails application i got the new value. Is this the intentional behaviour or am i missing something?

Thanks

**Comment by huacnlee** [comment]
What cache_store did you uses? `

**Comment by AkshayGoyal022** [comment]
I am sorry. I had a bug in my application. Thanks for the response nonetheless.

**Comment by rinoldsimon** [comment]
@AkshayGoyal022 Even I'm facing the same issue. How did you resolve it?
