### ISSUE TITLE
New configurations does not apply to cache.

### ISSUE THREAD

**Issue by crazyjin** [huacnlee/rails-settings-cached#155]
Application just use the old values in the cache. It a better idea to clear or update configuration values in cache every time just after rails-settings-cached loads a yml.

**Comment by huacnlee** [comment]
Use cache_prefix to increment version to clear cache.

```rb
class Setting < RailsSettings::Base
  cache_prefix { "v1" }
end
```

**Comment by acrolink** [comment]
> Use cache_prefix to increment version to clear cache.
> 
> ```ruby
> class Setting
>   cache_prefix { "v1" }
> end
> ```

I am facing the same issue. Happens randomly every couple of days. Do you mean that I should increment the cache prefix on every new launch of the Rails application?

If so, I guess it is better to set the `cache_prefix` dynamically to a unique and new `GUID` when the application starts.
