### ISSUE TITLE
Possibility to set setting type

### ISSUE THREAD

**Issue by TolichP** [huacnlee/rails-settings-cached#157]
Is it possible to set settings types? For example, something like this:

_setting.rb_
```
class Setting < RailsSettings::Base
  def fields
    {
      first_setting: Integer,
      second_setting: String,
      ...
    }
  end
end
```

I use rails-setting-cached and it is pretty good for storing some data for my project. But sometimes it would be useful to be able to set concrete type for each settings item and have it cast to this type whenever I try to get or set these settings.

If there is no possibility then may I create a PR?

**Comment by huacnlee** [comment]
#162 duplicate
