### ISSUE TITLE
Version2...

### ISSUE THREAD

**Issue by kenzooooo** [huacnlee/rails-settings-cached#159]
I want to manage in the file like the previous version. I want you to do this as another gem

**Comment by huacnlee** [comment]
You can keep use the 0.x version, I will still maintain it.

And you can try the new version in the new project, the 2.x design is better.

**Comment by wflanagan** [comment]
So, FYI.. related to this. A regular bundle on your gem bumped it to v2, which BROKE Heroku.  We didn't receive anything in the way of a DEPRECATION warning that said the upgrade would break (at least that I saw), and had a tense hour this morning while we figured out what was going on (as it looked more like an ActiveRecord database connectivity problem).  

I get and appreciate the desire to move forward, but I do think that some warning that you're doing breaking changes would be helpful.
