### ISSUE TITLE
get_all settings method disappeared

### ISSUE THREAD

**Issue by gfalasca** [huacnlee/rails-settings-cached#167]
Hi, not sure it is an issue, but cannot find the way to get_all the settings, included the ones declared through the field method.
In old releases I see that the Base class was subclassing the Settings class which contained the get_all method. Now the Base class just extends ActiveRecord::Base.

Thanks

**Comment by huacnlee** [comment]
```rb
Setting.all

Setting.where(thing_type: nil).all
```

**Comment by gfalasca** [comment]
Thanks, but as I said I would like to retrieve all the settings, not only the ones persisted in the database, also the ones defined with the field method in the Settings class.

**Comment by gfalasca** [comment]
Found, thx
