### ISSUE TITLE
如何更好的clear cache

### ISSUE THREAD

**Issue by ifsc01** [huacnlee/rails-settings-cached#174]
```
 def clear
    Setting.clear_cache
    redirect_to admin_settings_path, notice: "clear_cache更新成功"
  end

```
clear_cache  这个是不是不能清理所有cache?

https://cos.ap-beijing.myqcloud.com/dropshare-1252438752/Screen-Recording-2019-11-24-17-05-39-1574586339.mp4
这个一会是2一会3

**Comment by huacnlee** [comment]
你应该是没用分布式缓存，你可以看看目前 Rails 的缓存配置，确保是 memcached 或 redis 之类可以支持分布式的缓存

**Comment by ifsc01** [comment]
确实, 忘了这个地方了
