### ISSUE TITLE
Settings.all return empty unless setting is updated

### ISSUE THREAD

**Issue by phuongdh** [huacnlee/rails-settings-cached#176]
Hi,

Thanks for the gem, I tried it in my Rails app, so far so good, the default values are available to use. However, the DB table has no records at first.
```
# SELECT * FROM settings;
 id | var | value | created_at | updated_at 
----+-----+-------+------------+------------
(0 rows)
```
This is a problem because when I do `Setting.all` it returns an empty array, which is misleading and not useful when you want to show the settings to the user.

I think `all` can be overridden to return the full list of settings, and ideally they should come from the cache.

**Comment by ehayon** [comment]
I am running into the same issue - were you able to find a solution? @phuongdh

**Comment by huacnlee** [comment]
Version 2.3.0 changes:

```rb
Settting.editable_keys
=> Get all keys that allow to modify

Setting.readonly_keys
=> Get all readonly keys
```
