### ISSUE TITLE
多个实例，其中一个实例更新数据后，另一个实例直接Setting....请求依然是历史数据

### ISSUE THREAD

**Issue by zhangcaiyan** [huacnlee/rails-settings-cached#190]
你好，我举个例子，例如Setting有字段title，实例A的title更新为"火星"后，在实例A中Setting.title返回"火星",而实例BSetting.title返回的依然是以前的值。导致我每次修改setting数据的时候，每台服务器都要修改

**Comment by huacnlee** [comment]
你是不是 cache_store 没设置为 redis 或  memcached
