### ISSUE TITLE
Extend a model : uninitialized constant RailsSettings::Extend

### ISSUE THREAD

**Issue by Laurent774** [huacnlee/rails-settings-cached#192]
Hi,

With version 2.2.0, I would like to extend a model but  include RailsSettings::Extend return an error.

`NameError (uninitialized constant RailsSettings::Extend)`

I've missed something ?

Thanks.

Laurent

**Comment by huacnlee** [comment]
https://github.com/huacnlee/rails-settings-cached/blob/master/docs/backward-compatible-to-scoped-settings.md

**Comment by Laurent774** [comment]
Ok, then I've to add thing_id and thing_type to the settings table.

` t.integer :thing_id,   null: true
   t.string  :thing_type, null: true, limit: 30`

Thanks

**Comment by huacnlee** [comment]
@Laurent774 I am afraid that you should not do that. The new version of rails-settings-cached will not supports that feature.

That document was wrote for old version users to backward compatible.

It's looks like your case is used new version in new project. 

So, you may need use [ActiveRecord  Serialization](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize) to do that.

**Comment by Laurent774** [comment]
Thanks. Yes of course, it's better. And, in fact, I need only global application settings.
