### ISSUE TITLE
Can't edit values

### ISSUE THREAD

**Issue by fedefa** [huacnlee/rails-settings-cached#194]
I am getting an error when trying to edit an existing value. I am using this versions:

activeadmin (2.7.0)
activeadmin_settings_cached (2.0.0)
rails-settings-cached (0.5.6)

**Error:** 

```
NoMethodError at /admin/setting/update
undefined method `map' for <ActionController::Parameters {} permitted: true>:ActionController::Parameters
Did you mean?  tap
```

![Screenshot from 2020-10-14 01-11-48](https://user-images.githubusercontent.com/5441694/95942842-9d5b0c00-0dba-11eb-9be7-0d93ed80dc2b.png)

Thanks,
Best!

**Comment by huacnlee** [comment]
This issue caused by [activeadmin_settings_cached](https://github.com/artofhuman/activeadmin_settings_cached)
