### ISSUE TITLE
Support for metadata for fields

### ISSUE THREAD

**Issue by anujmiddha** [huacnlee/rails-settings-cached#210]
There can be scenarios where metadata is helpful for different fields. As an example, one might want to add description for different fields, which can then be shown on the form where the settings are updated.

This can be optional, and can be defined with the field itself,
```
field :host, type: :string, default: 'https://github.com', metadata: { description: 'Host URL }
```

**Comment by huacnlee** [comment]
Close by https://github.com/huacnlee/rails-settings-cached/pull/209#issuecomment-878301846
