### ISSUE TITLE
getting an undefined method for a setting

### ISSUE THREAD

**Issue by awunder** [huacnlee/rails-settings-cached#212]
Hi,
the whloe thing was working flawlessly until today, where i added a new Setting.. that results in a weird error:

![image](https://user-images.githubusercontent.com/13486613/122518501-49ef2c80-cfdf-11eb-986c-8face691b358.png)

as you can see, the console underneath has perfect knowledge of the setting the view above complains about..

my Setting model looks like this:

```
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  field :signin_redirect_target, default: "", type: :string
  field :admin_email, default: "adam@traderskew.com"
  field :default_tweet_text, default: "There is a new post for your you waiting on traderskew!"
  field :status_content, default: ""
  field :charities_enabled, default: "0", type: :boolean
  field :charities_total_enabled, default: "0", type: :boolean
  field :subscriptions_enabled, default: "0", type: :boolean
  field :blog_enabled, default: "0", type: :boolean
  field :status_enabled, default: "0", type: :boolean
  field :adjust_donation_amount_by, type: :float, default: 0.0
  field :visible_blog_posts, type: :integer, default: 3
  field :show_crypto_payments, default: "0", type: :boolean
  field :crypto_payments_content, default: ""
end
```

when i remove the `signin_redirect_target` it is all back working again.

is there anything i do wrong?

thanks,
Andreas

**Comment by huacnlee** [comment]
I just added a test 

https://github.com/huacnlee/rails-settings-cached/pull/213/files#diff-7a8e281a7904425262f05c7f58ec4c30b9f067e8bf815ebd1677b2fe2d5d5ebdR79

It work for me.

**Comment by huacnlee** [comment]
I can't found any issue in your message, would you please add the `admin/settings.html.erb` file content?

**Comment by awunder** [comment]
hi! sure, thx for looking into this!

made a zip from the view plus the nav partial which is part of the view..

[settings.zip](https://github.com/huacnlee/rails-settings-cached/files/6684469/settings.zip)

**Comment by huacnlee** [comment]
I found this issue, the form select can't support in current.

I will try to fix it, you can switch to write `<select>` without ActionView helper

**Comment by awunder** [comment]
ah, nice, thanks @huacnlee ! will give it a shot with html then..

**Comment by huacnlee** [comment]
version 2.6.0

**Comment by awunder** [comment]
@huacnlee - thats awesome, thanks so much, that fixed it!
