### ISSUE TITLE
Unable to use AR scope functionality

### ISSUE THREAD

**Issue by vitalinfo** [huacnlee/rails-settings-cached#215]
Version: 2.7.0

It's impossible to use ActiveRecord `scope` functionality, because of `lib/rails-settings/base.rb:40`

f.e.
```
class Setting < RailsSettings::Base
  scope :sort_by_id, ->(direction) { order(id: direction) }
end
```

**Comment by huacnlee** [comment]
Can you remove this?

You case looks like just use `Setting.order(...)` can do it.

**Comment by vitalinfo** [comment]
@huacnlee this's just an example, overall very bad experience override core rails methods in the gem

**Comment by huacnlee** [comment]
Version 2.7.1 has compatible with ActiveRecord scope
