### ISSUE TITLE
Disable RequestCache without Rails application

### ISSUE THREAD

**Issue by huacnlee** [huacnlee/rails-settings-cached#219]
In some cases (Sidekiq or other background job), RequestCache will can not expire. because it requirement Rails ActionController lifecycle to clean RequestCache.

There need a check to disable when not use in ActionController.

**Comment by huacnlee** [comment]
version 2.8.0 fixed this.

**Comment by andredriem** [comment]
This still seems to be an issue with 2.8.2. Manually clearing with  "Setting.clear_cache" as workaround.
