### ISSUE TITLE
Caching is buggy in Rails 5

### ISSUE THREAD

**Issue by dssjoblom** [huacnlee/rails-settings-cached#221]
The caching code for Rails 5 is incorrect, it never assigns the RequestStore value. See patch: 

https://github.com/dssjoblom/rails-settings-cached/commit/ba40acf9b6ac1d6d9dd13b36ed6fb05f0f15d415

**Comment by huacnlee** [comment]
Thanks, would you please make a PR, I will merged it.

**Comment by dssjoblom** [comment]
Great, I just sent the PR.

**Comment by huacnlee** [comment]
https://github.com/huacnlee/rails-settings-cached/releases/tag/v2.8.1
