### ISSUE TITLE
Rails 6.1.6.1 no longer loading Settings in /config/environments/*.rb

### ISSUE THREAD

**Issue by cweilemann** [huacnlee/rails-settings-cached#230]
Hey @huacnlee - I'm upgrading an app (slowly) to Rails 7, and in Rails 6.1.6.1, I'm getting the following error

```ruby
/Users/cweilemann/Projects/app/config/environments/production.rb:99:in `block in <top (required)>': uninitialized constant Setting (NameError)
Did you mean?  String
```

This didn't happen in Rails 5. I'm using the `zeitwork` gem. I checked the [Rails Guide for Autoloading and Reloading Constants](https://guides.rubyonrails.org/v6.1/autoloading_and_reloading_constants.html) but that didn't help. Any suggestions?

**Comment by tjku** [comment]
@cweilemann The answer is here: https://github.com/huacnlee/rails-settings-cached#readonly-field

> ```ruby
> # You must require_relative directly in Rails 6.1+ in config/environments/production.rb
> require_relative "../../app/models/setting"
> ```

**Comment by huacnlee** [comment]
Close too long old uncompleted issue, this may not exist in new version.

**Comment by rip747** [comment]
@tjku I owe you a coffee ☕ I have been stuck on this problem getting this to work on Rails 8 for 2 days now. Thank you 🤗
