### ISSUE TITLE
Updating a value doesn't invalidate cache in distributed system

### ISSUE THREAD

**Issue by matteeyah** [huacnlee/rails-settings-cached#233]
### Acutal

If I have two application nodes, one is the web worker, and the other one is a background worker, the following happens:

1. The background worker caches settings upon request
1. The web worker updates a setting
1. This doesn't invalidate the cache in the background worker
1. When executing the background worker it still has the old version of the settings cached and uses that

Maybe sidekiq doesn't process every single job as a new "request" and does some sort of "pooling" or long request 🤔 

### Expected

1. The background worker caches settings upon request
1. The web worker updates a setting
1. This invalidates the cache in the background worker
1. When executing the background worker it doesn't have the settings cached so it fetches the settings and caches the new value

### Workaround

Clear cache before performing each background job with

```ruby
before_perform { |_| Settings.clear_cache }
```

### System

I'm using `ActiveJob` with `Sidekiq` as a backend.

```
rails (7.0.4)
rails-settings-cached (2.8.3)
sidekiq (7.0.2)
```

**Comment by huacnlee** [comment]
rails-settings-cached has solved this problem:

https://github.com/huacnlee/rails-settings-cached/commit/0849bb203e46ba58663ff55288e2589ab501f210

The in-memory cache only enables in Web application process, because by this commit changes, is enabled by a Rails middleware, that now enable in background worker (Sidekiq).

**Comment by matteeyah** [comment]
> You have not given me the details, which cache storage did you use for? (Redis?)

The environment in which we were testing wasn't using Redis as the cache store. It used a file store (which was obviously different for every node). Switching to Redis solved this.

Thanks for the help!
