### ISSUE TITLE
Configurable cache storage feature

### ISSUE THREAD

**Issue by viralpraxis** [huacnlee/rails-settings-cached#234]
There are some cases when one doesn't want to use `Rails.cache` to store settings cache, i.e. consider multiple rails nodes each using its own memcached server (so each node has `Rails.cache` pointed to its own memcached node) -- for simplicity and consistency we'd like to use single shared redis server instance for settings caching.

ATM `Rails.cache` is hardcoded so there's no way to override the storage.

The solution is to make configurable option that can be set to any instance of `ActiveSupport::Cache::Store` (with default value of `Rails.cache`)

Are there any reasons this should not be implemented? If not, I'd be happy to provide a PR

**Comment by huacnlee** [comment]
Actually, you may not need to care about this. 

The cache is a cache, the cache of the RailsSetitngs like any other caches, we don't need to it for special.

So why do you want storage RailsSettings's cache in a special place? Why not keep them in you memcached (default Rails cache)?

**Comment by huacnlee** [comment]
> There are some cases when one doesn't want to use Rails.cache to store settings cache, i.e. consider multiple rails nodes each using its own memcached server (so each node has Rails.cache pointed to its own memcached node) -- for simplicity and consistency we'd like to use single shared redis server instance for settings caching.

By you mentioned, why not let the `Rails.cache` to a default storage. 
Are you still in using the `Rails.cache`? What this `Rails.cache` to do, why can not use `Rails.cache` to storage the RailsSettings's caches?

**Comment by viralpraxis** [comment]
Let me clarify the issue.

That's a common practice to have a distributed Rails application (i.e. with multiple RoR nodes running the same application) with separated caches (i.e. `Rails.cache`). For example. you might want to use separate `Memcached` server for each of these nodes.

In this situation, to ensure some sort of consistency of `RailsSetting` settings cache among all the nodes you have to use single cache storage (for instance, `Redis`) that will act as a cache for the nodes. To do so you have to able to configure the gem with that cache storage.
