### ISSUE TITLE
Version 2.9.0 breaks `type: :date_time`

### ISSUE THREAD

**Issue by stevenou** [huacnlee/rails-settings-cached#236]
Now getting `NameError: uninitialized constant RailsSettings::Fields::DateTime`

**Comment by huacnlee** [comment]
I just fixed this in v2.9.1

And actually, rails-settings-cached was not support `data_time`, it just used storage as string.

**Comment by stevenou** [comment]
Thanks for the quick fix! I didn't realize it was falling back to string on `date_time`. Any plans to support it?

**Comment by huacnlee** [comment]
I will
