### ISSUE TITLE
Change in behavior for integer

### ISSUE THREAD

**Issue by stevenou** [huacnlee/rails-settings-cached#237]
In versions prior to 2.9.0, one could set an integer setting to `nil` (or _not_ set it at all). Now, due to `deserialize` method that forces `to_i`, a `nil` value deserializes to `0` instead of `nil`.

Therefore, it breaks any code checking for `nil` setting. I believe `nil` should be a legitimate value that should be allowed for an `integer` setting.

**Comment by huacnlee** [comment]
Just released v2.9.2 to fix this issue.
