### ISSUE TITLE
ActiveAdmin interface for v2

### ISSUE THREAD

**Issue by ngelx** [huacnlee/rails-settings-cached#238]
## Quick an easy ActiveAdmin interface

This is an [ActiveAdmin](http://activeadmin.info/) extension to add the interface to handle [rails-setting-cached](https://github.com/huacnlee/rails-settings-cached) v2. For prior version I was using [activeadmin_setting_cached](https://github.com/artofhuman/activeadmin_settings_cached) but seems to be dead and does not support version > 2.

Link to the gist [ActiveAdmin interface for v2](https://gist.github.com/ngelx/9cd2f8989f2ffb2975cffbe937ba05e9)

**Comment by huacnlee** [comment]
Sorry, no plan to add UI things into Gem. This can be a part gem.
