### ISSUE TITLE
huacnlee/rails-settings-cached conflicts with ledermann/rails-settings

### ISSUE THREAD

**Issue by Roy-Gal-Git** [huacnlee/rails-settings-cached#250]
I'm working on an app that uses [ledermann/rails-settings](https://github.com/ledermann/rails-settings).
I found your gem as a perfect solution for a problem I'm trying to solve, but there're a couple of problems with it.
I know for a fact that it's a fork of [ledermann/rails-settings](https://github.com/ledermann/rails-settings) and that some class names, namespaces and method names are the same.
This causes some name collisions which will be solved if the namespaces would be changed.

For example - [RailsSettings::Configuration#initialize on ledermann/rails-settings](https://github.com/ledermann/rails-settings/blob/dd24f15f909c7e00dd10b67ee0bd4a839d533d22/lib/rails-settings/configuration.rb#L3) takes precedence over [RailsSettings::Configuration in your gem](https://github.com/huacnlee/rails-settings-cached/blob/2e16f8e819570d709fe1e5d1a5bb73712e24fb0a/lib/rails-settings/configuration.rb#L4) (which has no initializer) when I run schema migrations.

```
ArgumentError: wrong number of arguments (given 1, expected 0) (ArgumentError)

    RailsSettings::Configuration.new(*args.unshift(self), &block)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Another collision I found between the 2 gems is that both use the same `settings` table with different columns.

I know that I can open a PR with those fixes, but I'm worried about the edge case where I'll cause new name collisions for projects that are already using this gem 😆 

WDYT? Should I just fork the gem?

**Comment by Roy-Gal-Git** [comment]
UPDATE: I found [this doc file](https://github.com/huacnlee/rails-settings-cached/blob/main/docs/backward-compatible-to-scoped-settings.md) - is it still relevant if I want to still be able to create new scoped settings?

**Comment by huacnlee** [comment]
Because before I start this project, the rails-settings is not on maintaining or slow maintaining status.

And after some years this project have do a difference way for solve the settings. So I deside to remove scoped, because the Rails have some feature to do that, I want to keep this gem to keepking to simple for solve the settings.

I do this to replace rails-setings, not target to compibilit with that. So if you want use this gem, you must change your settings code with the rails-settings-cached's way to do.

**Comment by Roy-Gal-Git** [comment]
@huacnlee Thanks for the response!

So there's absolutely no way that you'll change the class names?
Because if you won't you'll always have name collisions and it won't be possible to use your gem with [ledermann/rails-settings](https://github.com/ledermann/rails-settings).

I'd like to migrate to your gem but it's not easy since both gems use the same table by default and it makes the migration very complicated.

**Comment by Roy-Gal-Git** [comment]
@huacnlee UPDATE: I opened a PR with the relevant fix.
https://github.com/huacnlee/rails-settings-cached/pull/252.
This issue can be closed once the PR is merged.
