### ISSUE TITLE
Force database access - Heroku

### ISSUE THREAD

**Issue by renanmzmendes** [huacnlee/rails-settings-cached#33]
I have deployed my application on Heroku and the caching behavior seems weird... It seems that when I change one of the settings dynamically, via a web interface, the other processes, such as workers and schedulers (and even other web dynos) don't notice the change and keep getting the old cached value.

Is there a way to force the value to be read via a database access? I can't restart my processes every time I make a change...

**Comment by Florian95** [comment]
:+1:

**Comment by runephilosof** [comment]
It would be nice if rails-settings-cached had a separate cache_store setting, such that you could use a different cache_store than what you are using for your Rails default.
Just as action_controller does: https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actionpack/lib/action_controller/railtie.rb#L40
