### ISSUE TITLE
Can not migrate db

### ISSUE THREAD

**Issue by ZuevEvgenii** [huacnlee/rails-settings-cached#38]
When deploy project I catch this error:

`rake db:migrate
PG::UndefinedTable: ERROR:  relation "settings" does not exist
LINE 5:                WHERE a.attrelid = '"settings"'::regclass`

**Comment by Ricardonacif** [comment]
Yeah I've faced the same problem and I do believe it should be added to readme

**Comment by jaswinder97** [comment]
is there any elegant solution yet?
