### ISSUE TITLE
Setting.save_default does not work when defaults[] is used in the model

### ISSUE THREAD

**Issue by vanboom** [huacnlee/rails-settings-cached#47]
When defaults are placed in the Setting model...
class Setting < RailsSettings::CachedSettings
  defaults[:test] = "Test Setting"
end

a call to...
Setting.save_default(:test, "A new Setting") returns nil and does not save the setting to the database.

Suggest modifying the software so save_default overrides and creates the database record.
thanks,
Don

**Comment by 1dot44mb** [comment]
@seaneshbaugh Thank you very much for this. I had the same problem and your explanation saved me.
