### ISSUE TITLE
Alternative ORM Support

### ISSUE THREAD

**Issue by ericraio** [huacnlee/rails-settings-cached#48]
Wasn't able to use this gem with mongoid. It would be nice if I didn't need ActiveRecord.

**Comment by Startouf** [comment]
It would also be nice to have support for cache databases like redis or memcache

**Comment by Startouf** [comment]
:'(

**Comment by merqlove** [comment]
I think it can be ORM agnostic.

**Comment by merqlove** [comment]
Anyone who need Mongoid support can try my fork. Seems that my adapter pattern works with Mongoid, as with AR. 
Specs still green, but excuse, no specs on Mongoid.
I think if we add some tests for Mongoid i can push these changes as PR.  
https://github.com/merqlove/rails-settings-cached/tree/be-orm-agnostic
