### ISSUE TITLE
Controller #Update Method

### ISSUE THREAD

**Issue by bertrand-caron** [huacnlee/rails-settings-cached#50]
Hey,

Amazing work you got going here !

I'm struck at a point which is not developed in the Readme but I am sure would interest more than just me. 
### How do you deal with updating the settings in the `SettingsController` once you have gathered your keys-values in a `params` hash or similar ?

```
class SettingsController < ApplicationController
  def index
    # to get all items for render list
    @settings = Setting.unscoped
  end

  def edit
    @setting = Setting.unscoped.find(params[:id])
  end

  def update
    # How to go from this ?
    Setting.foo = 'bar'
    # To :
    params.each do |key,value|
      Setting.send(key) = value # Obviously wrong
    end
  end
end
```

Keep up the good work !

**Comment by jmarceli** [comment]
I don't know if it's exactly what you were looking for but easy settings integration is described here http://stackoverflow.com/questions/7425798/how-to-create-a-form-for-the-rails-settings-plugin (after defining accessors you can use settings like any other model attribute). I use this approach in my Rails 4.2 based app.
