### ISSUE TITLE
`[]': undefined method `fetch' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by micrum** [huacnlee/rails-settings-cached#51]
I'm try to use rails-settings-cached with rails-settings-ui.
In production mode I have error 

```
`[]': undefined method `fetch' for nil:NilClass (NoMethodError)
```

Rails version: 4.1.4
Gem version: 0.4.1

**Comment by gentoid** [comment]
Having the same error with `rails-4.2.0` and `rails-settings-cached-0.4.1`

**Comment by huacnlee** [comment]
```ruby
obj = Rails.cache.read(cache_key)
```

Looks like `Rails.cache` not found, you need check your codes or Rails configuration.

**Comment by gentoid** [comment]
Yeah, you're right, after reporting this i checked what actually is going on. I found that `Rails.cache` returns the `nil`, and, of course, it hasn't `fetch` method. The issue was i tried to use cached settings in `environment/development.rb` when `Rails` is not fully loaded yet :smile:
