### ISSUE TITLE
Question: value stored in DB with dashes and dots

### ISSUE THREAD

**Issue by halpimded** [huacnlee/rails-settings-cached#52]
Hi, I'm wondering if this is the expected behavior, and why - I'll create a setting:

```
>> Setting.slinky = 0
>> Setting.slinky
>> 0
```

But when I view the data in the database its stored as:
```
--- 0
...
```

Main reason I'm asking is because I'm providing an edit form for admins and the dashes and dots are pre-populated in the form so I need to figure out why to avoid any issues.  Thanks.

**Comment by jeffshantz** [comment]
@halpimded The gem stores values as YAML.  This allows an object to be stored as a setting, as long as it can be serialized to YAML.
