### ISSUE TITLE
Read from DB directly

### ISSUE THREAD

**Issue by adisos** [huacnlee/rails-settings-cached#60]
For example, I want to read key from DB directly, not from cache. Is it possible?

**Comment by huacnlee** [comment]
Why? What difference?

**Comment by adisos** [comment]
I use two rails apps in one machine. They have shared classes, models and etc through rails engine. So when I change values from one app it's not see changes. 
It would be good if I can fetch values from DB something like that: `Setting.mykey!`

**Comment by mrj** [comment]
The exclamation mark variant is a good idea.

Another reason to bypass the cache is when you want to lock a setting when reading it (`SELECT...FOR UPDATE`) to control exclusive access to a resource.

**Comment by MichaelSp** [comment]
Same here. Value changes in the DB sometimes without the rails app noticing. So I need a way to invalidate the cache or reload directly.

**Comment by mlensment** [comment]
Second that.

**Comment by nykma** [comment]
+1 for this.

**Comment by prashantham** [comment]
+1. Is there any other way to reload setting?

**Comment by jpbullalayao** [comment]
Would love to load directly from DB as well

**Comment by idl3** [comment]
We can mark the settings (key/global) as stale and retrieve the new one for caching if we still want the performance gains. Much like a timestamp for last updated?

**Comment by brateq** [comment]
Same problem here, but on Elastic Beanstalk from Amazon. After update in form, rest of the app (like workers) doesn't know about change and still uses cached variable. How can I force to reload cached settings?

**Comment by drumaddict** [comment]
For object scoped settings, I found that this works:

```ruby
@page = Page.find(params[:id])

@page.settings.unscoped.find_by(var: :setting_id, thing_id: @page.id, thing_type: 'Page')
```

**Comment by erbunao** [comment]
I was wondering why was this closed? Was there a resolution/workaround to force reload?

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/blob/master/app/controllers/admin/site_configs_controller.rb#L24

**Comment by erbunao** [comment]
> https://github.com/ruby-china/homeland/blob/master/app/controllers/admin/site_configs_controller.rb#L24

@huacnlee Apologies for not getting what the line means. Could you elaborate a bit?

**Comment by huacnlee** [comment]
```irb
2.6.3 :002 > Setting.all
 => #<ActiveRecord::Relation [...]>
2.6.3 :002 > Setting.find_by(var: "setting_id")
```
