### ISSUE TITLE
默认值存储为正则表达式，编辑页面的时候出错 Unknown default value type Regexp

### ISSUE THREAD

**Issue by seaify** [huacnlee/rails-settings-cached#61]
class Setting < RailsSettings::CachedSettings
  defaults[:current_sms_verify_tpl_id] = 1
  defaults[:mobile_regex_format] = /\A1[3|4|5|8][0-9]\d{8}\z/
end

Unknown default value type Regexp

Extracted source (around line #44):
42
43
44
45
46
47
              
      default_setting_value_type = RailsSettingsUi.settings_klass.defaults[name.to_sym].class
      unless VALUE_TYPES_MAP.keys.include?(default_setting_value_type)
        raise RailsSettingsUi::UnknownDefaultValueType, "Unknown default value type #{default_setting_value_type}"
      end

      setting_value_type_class = VALUE_TYPES_MAP[default_setting_value_type]

**Comment by seaify** [comment]
@huacnlee @houndci  只有我碰到？

**Comment by huacnlee** [comment]
用字符串，这是要存到数据库的，无法支持这种特定类型
