### ISSUE TITLE
Possible regression in 0.4.5 - updates not reflected on next read

### ISSUE THREAD

**Issue by tovodeverett** [huacnlee/rails-settings-cached#73]
I believe I am seeing a regression in 0.4.5.  The following code works as expected with 0.4.4, but does not work as expected with 0.4.5:
```
p Setting.test# expect nil
Setting.test= 'foo'
p Setting.test# expect 'foo', get nil
```

It appears that writes do not invalidate or update the cache, whereas in 0.4.4 they did.

**Comment by sandrew** [comment]
+1
getting in test environment in RSpec

**Comment by savef** [comment]
This is an issue with Rails really, that it doesn't run `after_commit` callbacks in tests. See [here](https://github.com/grosser/test_after_commit) for more info, it's already fixed in Rails 5. For your Rails 4 tests DHH posted a solution [here](https://github.com/rails/rails/issues/16831). Basically, change this:
```ruby
test "hello world" do
  assert_equal "Hello, world!", hello_world
end
```
To this:
```ruby
uses_transaction :test_hello_world
test "hello world" do
  assert_equal "Hello, world!", hello_world
end
```

**Comment by wojtek-krysiak** [comment]
In my case I cleared all cache before assertion by `Rails.cache.clear`

**Comment by huacnlee** [comment]
Use new version 0.5.x

**Comment by tovodeverett** [comment]
Is this supposedly fixed in 0.5.3, or is there a later version of 0.5.x I should be using?  I'm seeing issues with my test suite when I update from 0.4.4 to 0.5.3.  The problems go away when I revert to 0.4.4.

**Comment by huacnlee** [comment]
@tovodeverett Which Rails version?

**Comment by tovodeverett** [comment]
Rails 4.2.5.1 currently.  When the regression first cropped up between 0.4.4 and 0.4.5 back in September, I was using Rails 4.2.4.

**Comment by justin808** [comment]
I have a PR on this issue #86.
