### ISSUE TITLE
Default settings returned as hash, persistent settings are strings

### ISSUE THREAD

**Issue by Arjeno** [huacnlee/rails-settings-cached#99]
When you use `Setting.get_all` you get a hash of settings. Default settings are returned as:

```ruby
{
  foo: { bar: 'foo' }
}
```

Persistent settings are returned as:

```ruby
{
  'foo.bar': 'foo'
}
```

This will return an inconsistent settings hash. I think one of these formats should be chosen, probably the string version as the hash would be too backwards incompatible.

**Comment by huacnlee** [comment]
You can't use nested default value, because in current rails-settings-cached has not supported that.

I suggest you change it like this:

```yml
foo_bar: 'foo'
```

**Comment by Arjeno** [comment]
Alright, thanks!
